apiVersion: k8s.nginx.org/v1
kind: VirtualServerRoute
metadata:
  name: coffee
  namespace: coffee
  labels:
    app: cafe
    route: coffee
spec:
  host: cafe.example.com
  upstreams:
  - name: coffee
    service: coffee-svc
    port: 80
  subroutes:
  - path: /coffee
    action:
      pass: coffee
    policies:
     - name: rate-limit-policy
    location-snippets: |
      # snippet defined in VSR
      proxy_set_header X-VSR-Name "Coffee";
    errorPages:
    - codes: [404]
      return:
        code: 200
        body: "Original resource not found, but success!"


