name: Mend

on:
  push:
    branches:
      - main
    paths-ignore:
      - site/**
      - examples/**
  workflow_dispatch:
    inputs:
      branch:
        type: string
        required: false
        default: main
  workflow_call:
    inputs:
      branch:
        type: string
        required: true

concurrency:
  group: ${{ github.ref_name }}-mend
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  scan:
    name: Mend
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ inputs.branch && inputs.branch || github.ref }}

      - name: Download agent
        run: curl -fsSLJO https://github.com/whitesource/unified-agent-distribution/releases/latest/download/wss-unified-agent.jar

      - name: Verify JAR
        run: jarsigner -verify wss-unified-agent.jar

      - name: Scan and upload
        env:
          PRODUCT_NAME: kubernetes-ingress-controller_${{ inputs.branch && inputs.branch || github.ref_name }}
          PROJECT_NAME: nic
        run: java -jar wss-unified-agent.jar -noConfig true -wss.url ${{ secrets.WSS_URL }} -apiKey ${{ secrets.WSS_NGINX_TOKEN }} -product $PRODUCT_NAME -project $PROJECT_NAME -d .
