name: Release NIC

on:
  workflow_dispatch:
    inputs:
      nic_version:
        description: "Version to release"
        required: true
        type: string
      chart_version:
        description: "Helm Chart version to release"
        required: true
        type: string
      release_branch:
        description: "Branch to release from"
        required: true
        type: string
      dry_run:
        description: "Dry Run?"
        type: boolean
        default: false

defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:
  tag:
    name: Create Tag on release branch in NIC repo
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - name: Checkout NIC repo
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
        with:
          ref: ${{ inputs.release_branch }}

      - name: Create new release Tag
        run: |
          branch="${{ inputs.release_branch }}"
          tag="v${{ inputs.nic_version }}"
          if git rev-parse --verify refs/tags/${tag}; then
            echo "Adding tag ${tag}."
            git tag -a ${tag} -m "Version ${tag#v*}"
            echo "Pushing to tag ${tag} to branch ${branch}"
            if ! ${{ inputs.dry_run }}; then
                git push origin "${tag}"
            else
                echo "DRY RUN not making any changes"
                git push --dry-run origin "${tag}"
            fi
          else
            echo "Warning: Tag ${tag} already exists.  Not making any changes"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.NGINX_PAT }}

  publish-helm-chart:
    name: Publish Helm Chart
    uses: ./.github/workflows/publish-helm.yml
    with:
      branch: ${{ inputs.release_branch }}
      ic_version: ${{ inputs.nic_version }}
      chart_version: ${{ inputs.chart_version }}
      nginx_helm_repo: true
    permissions:
      contents: write # for pushing to Helm Charts repository
      packages: write # for helm to push to GHCR
    secrets: inherit
